### ISSUE TITLE
Distinction between Global File Cache and Cloud Volumes Edge Cache isn't clear

### ISSUE THREAD

**Issue by TheFalldog** [NetAppDocs/cloud-manager-file-cache#10]
Page: [Cloud Volumes ONTAP licensing](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-licensing.html)

The licensing section for Cloud Volumes Edge Cache links to a website that doesn't have any license information on it.

**Comment by netapp-bcammett** [comment]
@netapp-tonacki, can we add a page to the Global File Cache documentation that addresses the following:

> Regarding the CV Edge Cache documentation, as someone not overly familiar with it, it's hard to draw a distinction between "Global File Cache" as a technical feature set and "CV Edge Cache" as seemingly the same functionality but built as a separate product from public documentation.

**Comment by TheFalldog** [comment]
FYI, it might be 10 edge nodes included with the initial license package. Not sure if/where that's documented but that's what I'm hearing from folks.

**Comment by netapp-tonacki** [comment]
Hi, 10 Edge node licenses would seem to make more sense since the user gets 1 license per 3 TiB CVO storage; and 30 TiB is minimum...

I am working with the Dev team and will be adding a section to the GFC docs about deploying CVEC so that it separate from the standard deploy and licensing mode with GFC.  Should be next week.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Status update: Still working with the team to get CVEC deployment details.

**Comment by ntap-bmegan** [comment]
Closed due to inactivity.
